site_name: My Notes
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.sections
    - navigation.top
    - navigation.expand
    - toc.integrate
    - search.suggest
    - content.code.copy

# This section will be automatically updated by update-nav.sh
nav:
  - Classes:
    - Freelance:
      - Nathens call 5925: classes/Freelance/nathens-call-5925.md
  - Freelance:
    - Nathens call 5925: classes/Freelance/nathens-call-5925.md
  - Daily:
    - 2025 04 16: daily/2025-04-16.md
    - README: daily/README.md
  - Ideas:
    - README: ideas/README.md
  - Jobs:
    - Hole In One:
      - HIOUSA Quote Structure–Rebuild+Retainer: jobs/Hole-In-One/HIOUSA-Quote-Structure–Rebuild+Retainer.md
      - HIOUSA Rebuild–Strategic Overview: jobs/Hole-In-One/HIOUSA-Rebuild–Strategic-Overview.md
      - HIOUSA Retainer Model–Internal Plan: jobs/Hole-In-One/HIOUSA-Retainer-Model–Internal-Plan.md
      - Amy fanter profile: jobs/Hole-In-One/amy-fanter-profile.md
      - Hiousa site review: jobs/Hole-In-One/hiousa-site-review.md
      - Organization overview: jobs/Hole-In-One/organization-overview.md
      - Pih organization research: jobs/Hole-In-One/pih-organization-research.md
      - Project notes hiousa: jobs/Hole-In-One/project-notes-hiousa.md
    - E9digital:
      - 1 hour crash: jobs/e9digital/1-hour-crash.md
      - Day one test: jobs/e9digital/Day-one-test.md
      - Crm implementation notes: jobs/e9digital/crm-implementation-notes.md
      - E9digital overview: jobs/e9digital/e9digital-overview.md
      - Gohighlevel client training plan: jobs/e9digital/gohighlevel-client-training-plan.md
      - Gohighlevel training checklist: jobs/e9digital/gohighlevel-training-checklist.md
      - Meeting prep: jobs/e9digital/meeting-prep.md
    - 182 remodel site: jobs/182-remodel-site.md
    - Amy Fanter: jobs/Amy-Fanter.md
    - README: jobs/README.md
  - Hole In One:
    - HIOUSA Quote Structure–Rebuild+Retainer: jobs/Hole-In-One/HIOUSA-Quote-Structure–Rebuild+Retainer.md
    - HIOUSA Rebuild–Strategic Overview: jobs/Hole-In-One/HIOUSA-Rebuild–Strategic-Overview.md
    - HIOUSA Retainer Model–Internal Plan: jobs/Hole-In-One/HIOUSA-Retainer-Model–Internal-Plan.md
    - Amy fanter profile: jobs/Hole-In-One/amy-fanter-profile.md
    - Hiousa site review: jobs/Hole-In-One/hiousa-site-review.md
    - Organization overview: jobs/Hole-In-One/organization-overview.md
    - Pih organization research: jobs/Hole-In-One/pih-organization-research.md
    - Project notes hiousa: jobs/Hole-In-One/project-notes-hiousa.md
  - E9digital:
    - 1 hour crash: jobs/e9digital/1-hour-crash.md
    - Day one test: jobs/e9digital/Day-one-test.md
    - Crm implementation notes: jobs/e9digital/crm-implementation-notes.md
    - E9digital overview: jobs/e9digital/e9digital-overview.md
    - Gohighlevel client training plan: jobs/e9digital/gohighlevel-client-training-plan.md
    - Gohighlevel training checklist: jobs/e9digital/gohighlevel-training-checklist.md
    - Meeting prep: jobs/e9digital/meeting-prep.md
  - Projects:
    - Css relitive units: projects/css-relitive-units.md
    - Robot face: projects/robot-face.md
  - References:
    - CSS resources: references/CSS-resources.md
    - GoHighLevel: references/GoHighLevel.md
    - README: references/README.md
  - Index: index.md
  - Markdown cheatsheet: markdown-cheatsheet.md
