site_name: My Notes
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.sections
    - navigation.top
    - navigation.expand
    - toc.integrate
    - search.suggest
    - content.code.copy

# This section will be automatically updated by update-nav.sh
nav:
  - Daily:
    - 2025 04 16: daily/2025-04-16.md
    - README: daily/README.md
  - Ideas:
    - README: ideas/README.md
  - Jobs:
    - 182 remodel site: jobs/182-remodel-site.md
    - README: jobs/README.md
  - Projects:
    - Css relitive units: projects/css-relitive-units.md
    - Robot face: projects/robot-face.md
  - References:
    - CSS resources: references/CSS-resources.md
    - README: references/README.md
  - Index: index.md
  - Markdown cheatsheet: markdown-cheatsheet.md
